name: CI
on:
   push:
      branches:
      - main
   pull_request:
      branches:
      - main
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  name: Checkout
         uses: actions/checkout@v2
      -  uses: actions/setup-node@v2.1.4
         with:
           node-version: 14.16.0
      -  name: Install ajv-cli first
         run: npm install -g ajv-cli markdown-table-cli
      -  name: Execute script
         run: sh ./scripts/build.sh